try:
    import tomllib as toml

    def myload(filename):
        with open(filename, 'rb') as f:
            proj = toml.load(f)
        return proj

except Exception:
    import toml

    def myload(filename):
        return toml.load(filename)


def get_version_from_pyproject_toml(filename):
    """
    Find the value assigned to __version__ in pyproject.toml
    """
    proj = myload(filename)
    return proj['project']['version']


if __name__ == "__main__":
    import sys

    infilename = sys.argv[1]
    outfilename = sys.argv[2]
    version = get_version_from_pyproject_toml(infilename)
    with open(outfilename, 'w') as f:
        print('# Do not edit this file!', file=f)
        print('# This file is generated by a script.  To update the', file=f)
        print('# version, change the value in pyproject.toml.\n', file=f)
        print(f'__version__ = "{version}"', file=f)
