
// Do not edit this file!
// This file was generated by a script.

#ifndef UFUNCLAB_DEBYE1_GENERATED_H
#define UFUNCLAB_DEBYE1_GENERATED_H

double debye1(const double);

#endif  // UFUNCLAB_DEBYE1_GENERATED_H
