
name: Run on windows-2025-vs2026

on: workflow_dispatch

jobs:
  windows-msvc:

    strategy:
      matrix:
        numpy-version: ['2.2.6', '2.3.5', '2.4.4']
        python-version: ['3.13', '3.14']
        exclude:
          - numpy-version: '2.2.6'
            python-version: '3.14'
          - numpy-version: '2.3.5'
            python-version: '3.14'
      fail-fast: false

    runs-on: windows-2025-vs2026

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
        cache: 'pip'
        cache-dependency-path: 'environment.yml'

    - name: Install Python dependencies
      run: |
        pip install numpy==${{ matrix.numpy-version }} meson ninja meson-python pytest toml

    - name: Build and install ufunclab
      run: |
        pip -v install --no-build-isolation -Csetup-args="--vsenv" .

    - name: Test
      run: |
        pytest --pyargs ufunclab
